steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true","appengine:deploy"]
#  - name: gcr.io/cloud-builders/docker
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/jamsession", "--build-arg=JAR_FILE=target/jamsession-0.0.1.jar", "."]
#images: ["gcr.io/$PROJECT_ID/jamsession"]