INSERT INTO users VALUES
    (NULL,'luisao@example.com', NULL, 'Anderson', 'Silva', '1980-01-01', 97331, 'Corvallis', 'OR'),
    (NULL,'jonas@example.com', NULL, 'Jonas', 'Goncalves', '1981-02-02', 97035, 'Portland', 'OR'),
    (NULL,'fejsa@example.com', NULL, 'Ljubomir', 'Fejsa', '1982-03-03', 	97333, 'Corvallis', 'OR');

INSERT INTO instruments VALUES
    (NULL, 'Violin', 'String'),
    (NULL, 'Guitar', 'String'),
    (NULL, 'Cello', 'String'),
    (NULL, 'Harp', 'String'),
    (NULL, 'Veena', 'String'),
    (NULL, 'Sitar', 'String'),
    (NULL, 'Viola', 'String'),
    (NULL, 'Mandolin', 'String'),
    (NULL, 'Banjo', 'String'),
    (NULL, 'Ukulele', 'String'),
    (NULL, 'Lute', 'String'),
    (NULL, 'Drums', 'Percussion'),
    (NULL, 'Mridangam', 'Percussion'),
    (NULL, 'Tabla', 'Percussion'),
    (NULL, 'Xylophone', 'Percussion'),
    (NULL, 'Snare drum', 'Percussion'),
    (NULL, 'Cymbal', 'Percussion'),
    (NULL, 'Triangle', 'Percussion'),
    (NULL, 'Bass drum', 'Percussion'),
    (NULL, 'Maracas', 'Percussion'),
    (NULL, 'Chimes', 'Percussion'),
    (NULL, 'Tambourine', 'Percussion'),
    (NULL, 'Timpani', 'Percussion'),
    (NULL, 'Marimba', 'Percussion'),
    (NULL, 'Piano', 'Keyboard'),
    (NULL, 'Harmonium', 'Keyboard'),
    (NULL, 'Celeste', 'Keyboard'),
    (NULL, 'Pipe organ', 'Keyboard'),
    (NULL, 'Accordion', 'Keyboard'),
    (NULL, 'Claviola', 'Keyboard'),
    (NULL, 'Harpsichord', 'Keyboard'),
    (NULL, 'Organ', 'Keyboard'),
    (NULL, 'Synthesiser', 'Keyboard'),
    (NULL, 'Harmonica', 'Keyboard'),
    (NULL, 'Flute', 'Brass/Wind'),
    (NULL, 'Trumpet', 'Brass/Wind'),
    (NULL, 'Saxophone', 'Brass/Wind'),
    (NULL, 'Mouth organ', 'Brass/Wind'),
    (NULL, 'Piccolo', 'Brass/Wind'),
    (NULL, 'Trombone', 'Brass/Wind'),
    (NULL, 'French horn', 'Brass/Wind'),
    (NULL, 'Tuba', 'Brass/Wind'),
    (NULL, 'Euphonium', 'Brass/Wind'),
    (NULL, 'Cornet', 'Brass/Wind'),
    (NULL, 'Oboe', 'Brass/Wind'),
    (NULL, 'Clarinet', 'Brass/Wind'),
    (NULL, 'Bassoon', 'Brass/Wind');

INSERT INTO genres VALUES
    (NULL, 'Blues'),
    (NULL, 'Classical'),
    (NULL, 'Country'),
    (NULL, 'Electronic'),
    (NULL, 'Folk'),
    (NULL, 'Hip hop'),
    (NULL, 'Jazz'),
    (NULL, 'Pop'),
    (NULL, 'R&B'),
    (NULL, 'Rock'),
    (NULL, 'Metal'),
    (NULL, 'Punk'),
    (NULL, 'African'),
    (NULL, 'Asian'),
    (NULL, 'Middle Eastern'),
    (NULL, 'Caribbean'),
    (NULL, 'Latin');
